//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.6
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Home</summary>
	[PublishedModel("home")]
	public partial class Home : PublishedContentModel, IHomePageControls, IServicesControls, ITestimonialsControls, IWhyChooseUsControls
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const string ModelTypeAlias = "home";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Home(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Banner Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("bannerTitle")]
		public string BannerTitle => HomePageControls.GetBannerTitle(this);

		///<summary>
		/// Search Bar 1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("searchBar1")]
		public string SearchBar1 => HomePageControls.GetSearchBar1(this);

		///<summary>
		/// Search Bar 2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("searchBar2")]
		public string SearchBar2 => HomePageControls.GetSearchBar2(this);

		///<summary>
		/// Search Bar 3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("searchBar3")]
		public string SearchBar3 => HomePageControls.GetSearchBar3(this);

		///<summary>
		/// First Column Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("firstColumnHeading")]
		public IHtmlString FirstColumnHeading => ServicesControls.GetFirstColumnHeading(this);

		///<summary>
		/// First Column Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("firstColumnImage")]
		public IPublishedContent FirstColumnImage => ServicesControls.GetFirstColumnImage(this);

		///<summary>
		/// First Column Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("firstColumnText")]
		public IHtmlString FirstColumnText => ServicesControls.GetFirstColumnText(this);

		///<summary>
		/// Second Column Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("secondColumnHeading")]
		public IHtmlString SecondColumnHeading => ServicesControls.GetSecondColumnHeading(this);

		///<summary>
		/// Second Column Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("secondColumnImage")]
		public IPublishedContent SecondColumnImage => ServicesControls.GetSecondColumnImage(this);

		///<summary>
		/// Second Column Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("secondColumnText")]
		public IHtmlString SecondColumnText => ServicesControls.GetSecondColumnText(this);

		///<summary>
		/// Services Header
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("servicesHeader")]
		public IHtmlString ServicesHeader => ServicesControls.GetServicesHeader(this);

		///<summary>
		/// Third Column Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("thirdColumnHeading")]
		public IHtmlString ThirdColumnHeading => ServicesControls.GetThirdColumnHeading(this);

		///<summary>
		/// Third Column Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("thirdColumnImage")]
		public IPublishedContent ThirdColumnImage => ServicesControls.GetThirdColumnImage(this);

		///<summary>
		/// Third Column Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("thirdColumnText")]
		public IHtmlString ThirdColumnText => ServicesControls.GetThirdColumnText(this);

		///<summary>
		/// Aryan Dang Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("aryanDangText")]
		public IHtmlString AryanDangText => TestimonialsControls.GetAryanDangText(this);

		///<summary>
		/// Testimonials Header
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("testimonialsHeader")]
		public IHtmlString TestimonialsHeader => TestimonialsControls.GetTestimonialsHeader(this);

		///<summary>
		/// Testimonials Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("testimonialsImage")]
		public IPublishedContent TestimonialsImage => TestimonialsControls.GetTestimonialsImage(this);

		///<summary>
		/// About Us Header
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("aboutUsHeader")]
		public IHtmlString AboutUsHeader => WhyChooseUsControls.GetAboutUsHeader(this);

		///<summary>
		/// About Us Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("aboutUsImage")]
		public IPublishedContent AboutUsImage => WhyChooseUsControls.GetAboutUsImage(this);

		///<summary>
		/// Bullet Point 1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("bulletPoint1")]
		public IHtmlString BulletPoint1 => WhyChooseUsControls.GetBulletPoint1(this);

		///<summary>
		/// Bullet Point 2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("bulletPoint2")]
		public IHtmlString BulletPoint2 => WhyChooseUsControls.GetBulletPoint2(this);

		///<summary>
		/// Bullet Point 3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("bulletPoint3")]
		public IHtmlString BulletPoint3 => WhyChooseUsControls.GetBulletPoint3(this);

		///<summary>
		/// Bullet Point 4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("bulletPoint4")]
		public IHtmlString BulletPoint4 => WhyChooseUsControls.GetBulletPoint4(this);

		///<summary>
		/// Main Text Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("mainTextHeading")]
		public IHtmlString MainTextHeading => WhyChooseUsControls.GetMainTextHeading(this);
	}
}
