//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureRoom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbo_RetrieveItemsUsers
    {
        public string ID { get; set; }
        public string FullName { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> AgeAbove18AndHonesty { get; set; }
        public Nullable<bool> ConsentToData { get; set; }
    }
}
