//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureRoom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbo_LostItems
    {
        public string ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Postcode { get; set; }
        public string ItemType { get; set; }
        public string ImagePath { get; set; }
        public Nullable<System.DateTime> DatePosted { get; set; }
        public string UserTitle { get; set; }
        public string UserFullName { get; set; }
        public string UserEmailAddress { get; set; }
        public string Question1 { get; set; }
        public string Answer1 { get; set; }
        public string Question2 { get; set; }
        public string Answer2 { get; set; }
        public string Question3 { get; set; }
        public string Answer3 { get; set; }
    }
}
