//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureRoom.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TreasureRoomEntities : DbContext
    {
        public TreasureRoomEntities()
            : base("name=TreasureRoomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dbo_ItemTypes> dbo_ItemTypes { get; set; }
        public virtual DbSet<dbo_LostItems> dbo_LostItems { get; set; }
        public virtual DbSet<dbo_Titles> dbo_Titles { get; set; }
    
        public virtual ObjectResult<Get_LostItems_Result> Get_LostItems()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_LostItems_Result>("Get_LostItems");
        }
    
        public virtual ObjectResult<Get_ItemTypes_Result> Get_ItemTypes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_ItemTypes_Result>("Get_ItemTypes");
        }
    
        public virtual int Post_LostItems(string iD, string title, string description, string postcode, string itemType, string imagePath, Nullable<System.DateTime> datePosted, string userTitle, string userFullName, string userEmailAddress)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var titleParameter = title != null ?
                new ObjectParameter("Title", title) :
                new ObjectParameter("Title", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var postcodeParameter = postcode != null ?
                new ObjectParameter("Postcode", postcode) :
                new ObjectParameter("Postcode", typeof(string));
    
            var itemTypeParameter = itemType != null ?
                new ObjectParameter("ItemType", itemType) :
                new ObjectParameter("ItemType", typeof(string));
    
            var imagePathParameter = imagePath != null ?
                new ObjectParameter("ImagePath", imagePath) :
                new ObjectParameter("ImagePath", typeof(string));
    
            var datePostedParameter = datePosted.HasValue ?
                new ObjectParameter("DatePosted", datePosted) :
                new ObjectParameter("DatePosted", typeof(System.DateTime));
    
            var userTitleParameter = userTitle != null ?
                new ObjectParameter("UserTitle", userTitle) :
                new ObjectParameter("UserTitle", typeof(string));
    
            var userFullNameParameter = userFullName != null ?
                new ObjectParameter("UserFullName", userFullName) :
                new ObjectParameter("UserFullName", typeof(string));
    
            var userEmailAddressParameter = userEmailAddress != null ?
                new ObjectParameter("UserEmailAddress", userEmailAddress) :
                new ObjectParameter("UserEmailAddress", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Post_LostItems", iDParameter, titleParameter, descriptionParameter, postcodeParameter, itemTypeParameter, imagePathParameter, datePostedParameter, userTitleParameter, userFullNameParameter, userEmailAddressParameter);
        }
    }
}
