//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureRoom.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TreasureRoomEntities1 : DbContext
    {
        public TreasureRoomEntities1()
            : base("name=TreasureRoomEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dbo_ItemTypes> dbo_ItemTypes { get; set; }
    
        public virtual ObjectResult<get_ItemTypes_Result> get_ItemTypes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_ItemTypes_Result>("get_ItemTypes");
        }
    }
}
